/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":movecraft-api"))
    compileOnly("org.spigotmc:spigot:1.20.6-R0.1-SNAPSHOT")
}

description = "Movecraft-v1_20"
