/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":movecraft-api"))
    compileOnly(libs.org.spigotmc.spigot.x1)
}

description = "Movecraft-v1_20"
