/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "movecraft-parent"
include(":movecraft-v1_18")
include(":movecraft-v1_20")
include(":movecraft-api")
include(":datapack")
project(":movecraft-v1_18").projectDir = file("modules/v1_18")
project(":movecraft-v1_20").projectDir = file("modules/v1_20")
project(":movecraft-api").projectDir = file("modules/api")
project(":datapack").projectDir = file("modules/datapack")
