/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":movecraft-api"))
    compileOnly("org.spigotmc:spigot:1.19.4-R0.1-SNAPSHOT")
}

description = "Movecraft-v1_19"
