name: Movecraft
softdepend: [WorldGuard, WorldEdit, Cannons, Vault]
version: 3.1.X80
#version: ${env.BUILD_NUMBER}
description: The original flight and movement plugin for minecraft.
author: BaccaYarro
website: http://www.youtube.com/BaccaYarro
main: net.countercraft.movecraft.Movecraft
database: false
commands:
  release:
    description: Releases your craft
    usage: /release
  pilot:
    description: Pilots the craft at your feet
    usage: /pilot [crafttypename]
  craftreport:
    description: reports on all active craft in the world you are in
    usage: /craftreport
  cruise:
    description: Starts your craft cruising
    usage: /cruise [north|south|east|west]
  cruiseoff:
    description: Stops your craft from cruising
    usage: /cruiseoff
  rotateleft:
    description: Rotates your craft left
    usage: /rotateleft
  rotateright:
    description: Rotates your craft right
    usage: /rotateright
  manoverboard:
    description: If enabled, returns you to a craft you have fallen out of
    usage: /manoverboard
