name: Movecraft
softdepend: [WorldGuard, WGCustomFlags]
version: ${project.version}
#version: ${env.BUILD_NUMBER}
description: The original flight and movement plugin for minecraft.
authors: [BaccaYarro, cccm5, TylerS1066, eirik1996]
website: https://github.com/APDevTeam/Movecraft
main: net.countercraft.movecraft.Movecraft
database: false
commands:
  movecraft:
    description: base movecraft command
    usage: /movecraft [reloadtypes]
  release:
    description: Releases your craft
    usage: /release
  pilot:
    description: Pilots the craft at your feet
    usage: /pilot [crafttypename]
  contacts:
    description: reports on all crafts within detection range
    usage: /contacts <page>
  craftreport:
    description: reports on all active craft in the world you are in
    usage: /craftreport <page>
  cruise:
    description: Starts your craft cruising
    usage: /cruise [north|south|east|west|on|off]
  rotate:
    description: Rotates your craft
    usage: /rotate [right|left]
  manoverboard:
    description: If enabled, returns you to a craft you have fallen out of
    usage: /manoverboard
  scuttle:
    description: Sinks piloted craft
    usage: /scuttle