/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("io.papermc.paperweight.userdev")
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

dependencies {
    api(project(":movecraft-api"))
    paperweight.paperDevBundle("1.18.2-R0.1-SNAPSHOT")
}

description = "Movecraft-v1_18"
paperweight.reobfArtifactConfiguration = io.papermc.paperweight.userdev.ReobfArtifactConfiguration.REOBF_PRODUCTION
