/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.io.papermc.paper.paper.api)
    api(libs.org.openjdk.jmh.jmh.core)
    api(libs.org.openjdk.jmh.jmh.generator.annprocess)
    api(libs.org.roaringbitmap.roaringbitmap)
    api(libs.it.unimi.dsi.fastutil)
    api(libs.net.kyori.adventure.api)
    api(libs.net.kyori.adventure.platform.bukkit)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.junit.junit)
    testImplementation(libs.org.hamcrest.hamcrest.library)
    compileOnly(libs.org.jetbrains.annotations)
}

tasks {
    compileJava {
        options.compilerArgs.addAll(listOf(
            "--add-exports", "java.base/jdk.internal.vm.annotation=ALL-UNNAMED"
        ))
    }
}

description = "Movecraft-API"
