name: Java CI

on: 
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '22 13 * * 6'

jobs:
  # Build Movecraft
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Movecraft
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Build with Gradle
        run: ./gradlew clean shadowJar

      - name: Stage jar
        run: mkdir staging && cp modules/Movecraft/build/libs/Movecraft.jar staging && mv staging/Movecraft.jar staging/Movecraft_$GITHUB_SHA.jar
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: Movecraft_Dev-Build
          path: staging/Movecraft_*.jar
