name: Gradle CI

on: 
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '22 13 * * 6'
  release:
    types: [created, prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Movecraft
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Build with Gradle
        run: ./gradlew clean shadowJar --parallel

      - name: Publish to GitHub Packages
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: ./gradlew publish --parallel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PaperMC Hangar
        if: ${{ github.event_name == 'release' }}
        run: ./gradlew publishPluginPublicationToHangar --parallel
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}

      - name: Stage jar for Actions
        if: ${{ github.event_name != 'release' }}
        run: mkdir staging && cp Movecraft/build/libs/Movecraft.jar staging && mv staging/Movecraft.jar staging/Movecraft_$GITHUB_SHA.jar
      - name: Upload jar to Actions
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: Movecraft_Dev-Build
          path: staging/Movecraft_*.jar

      - name: Stage jar for Release
        if: ${{ github.event_name == 'release' }}
        run: mkdir staging && cp Movecraft/build/libs/Movecraft.jar staging && mv staging/Movecraft.jar staging/Movecraft_${{ github.event.release.tag_name }}.jar
      - name: Upload jar to Release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          files: staging/Movecraft_${{ github.event.release.tag_name }}.jar
