name: Publish package to GitHub Packages

on:
  workflow_dispatch:
  release:
    types: [created, prereleased]

jobs:
  # Build Movecraft
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Movecraft
      uses: actions/checkout@v1
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -T 1C -B package --file pom.xml

    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
