name: Publish package to GitHub Packages

on:
  workflow_dispatch:
  release:
    types: [created, prereleased]

jobs:
  # Build 1.14.4 NMS
  pillage_1_14_4:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 13 # 1.14.4 can be built with Java 8 to Java 13
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '13'
      - name: Cache 1.14.4 Maven package
        id: cachePillage
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/org/bukkit/craftbukkit/1.14.4-R0.1-SNAPSHOT/
          key: ${{ runner.os }}-1.14.4
          restore-keys: ${{ runner.os }}-1.14.4
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2_1.14.4
          restore-keys: ${{ runner.os }}-m2_1.14.4

      - name: Setup BuildTools
        run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Check 1.14.4
        id: pillage
        run: test -f ~/.m2/repository/org/bukkit/craftbukkit/1.14.4-R0.1-SNAPSHOT/craftbukkit-1.14.4-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Build 1.14.4
        if: steps.pillage.outputs.sucess != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.14.4 --compile craftbukkit

  # Build 1.15.2 NMS
  bees_1_15_2:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 14 # 1.15.2 can be built with Java 8 to Java 14
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '14'
      - name: Cache 1.15.2 Maven package
        id: cacheBees
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/org/bukkit/craftbukkit/1.15.2-R0.1-SNAPSHOT/
          key: ${{ runner.os }}-1.15.2
          restore-keys: ${{ runner.os }}-1.15.2
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2_1.15.2
          restore-keys: ${{ runner.os }}-m2_1.15.2

      - name: Setup BuildTools
        run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Check 1.15.2
        id: bees
        run: test -f ~/.m2/repository/org/bukkit/craftbukkit/1.15.2-R0.1-SNAPSHOT/craftbukkit-1.15.2-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Build 1.15.2
        if: steps.bees.outputs.sucess != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.15.2 --compile craftbukkit

  # Build 1.16.5 NMS
  nether_1_16_5:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 16 # 1.16.5 can be built with Java 8 to Java 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '16'
      - name: Cache 1.16.5 Maven package
        id: cacheNether
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/org/bukkit/craftbukkit/1.16.5-R0.1-SNAPSHOT/
          key: ${{ runner.os }}-1.16.5
          restore-keys: ${{ runner.os }}-1.16.5
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2_1.16.5
          restore-keys: ${{ runner.os }}-m2_1.16.5

      - name: Setup BuildTools
        run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Check 1.16.5
        id: nether3
        run: test -f ~/.m2/repository/org/bukkit/craftbukkit/1.16.5-R0.1-SNAPSHOT/craftbukkit-1.16.5-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Build 1.16.5
        if: steps.nether3.outputs.sucess != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.16.5 --compile craftbukkit

  # Build 1.17.1 NMS
  goats_1_17_1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17 # 1.17.1 can be built with Java 16 to Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '17'
      - name: Cache 1.17.1 Maven package
        id: cacheGoats
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository/org/spigotmc/spigot/1.17.1-R0.1-SNAPSHOT/
            ~/.m2/repository/org/spigotmc/spigot-parent/
            ~/.m2/repository/org/spigotmc/minecraft-server/
          key: ${{ runner.os }}-spigot-1.17.1-all
          restore-keys: ${{ runner.os }}-spigot-1.17.1-all
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2_1.17.1
          restore-keys: ${{ runner.os }}-m2_1.17.1

      - name: Setup BuildTools
        run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Check 1.17.1 Spigot
        id: goats
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.17.1-R0.1-SNAPSHOT/spigot-1.17.1-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Check 1.17.1 Spigot (Mojang)
        id: goatsMojang
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.17.1-R0.1-SNAPSHOT/spigot-1.17.1-R0.1-SNAPSHOT-remapped-mojang.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Check 1.17.1 Spigot (Obf)
        id: goatsObf
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.17.1-R0.1-SNAPSHOT/spigot-1.17.1-R0.1-SNAPSHOT-remapped-obf.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Build 1.17.1
        if: steps.goats.outputs.sucess != 'true' || steps.goatsMojang.outputs.sucess != 'true' || steps.goatsObf.outputs.sucess != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.17.1 --remapped


  # Build 1.18 NMS
  caves_1_18-rc3:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17 # 1.18 can only be built with Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '17'
      - name: Cache 1.18 Maven package
        id: cacheCaves
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository/org/spigotmc/spigot/1.18-R0.1-SNAPSHOT/
            ~/.m2/repository/org/spigotmc/spigot-parent/
            ~/.m2/repository/org/spigotmc/minecraft-server/
          key: ${{ runner.os }}-spigot-1.18-all
          restore-keys: ${{ runner.os }}-spigot-1.18-all
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2_1.18
          restore-keys: ${{ runner.os }}-m2_1.18

      - name: Setup BuildTools
        run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Check 1.18 Spigot
        id: caves
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.18-R0.1-SNAPSHOT/spigot-1.18-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Check 1.18 Spigot (Mojang)
        id: cavesMojang
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.18-R0.1-SNAPSHOT/spigot-1.18-R0.1-SNAPSHOT-remapped-mojang.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Check 1.18 Spigot (Obf)
        id: cavesObf
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.18-R0.1-SNAPSHOT/spigot-1.18-R0.1-SNAPSHOT-remapped-obf.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Build 1.18
        if: steps.caves.outputs.sucess != 'true' || steps.cavesMojang.outputs.sucess != 'true' || steps.cavesObf.outputs.sucess != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.18 --remapped

  # Build Movecraft
  publish:
    runs-on: ubuntu-latest
    needs: [pillage_1_14_4, bees_1_15_2, nether_1_16_5, goats_1_17_1, caves_1_18]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Movecraft
        uses: actions/checkout@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '16'
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2
      - name: Cache 1.14.4 Maven package
        id: cachePillage
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/org/bukkit/craftbukkit/1.14.4-R0.1-SNAPSHOT/
          key: ${{ runner.os }}-1.14.4
          restore-keys: ${{ runner.os }}-1.14.4
      - name: Cache 1.15.2 Maven package
        id: cacheBees
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/org/bukkit/craftbukkit/1.15.2-R0.1-SNAPSHOT/
          key: ${{ runner.os }}-1.15.2
          restore-keys: ${{ runner.os }}-1.15.2
      - name: Cache 1.16.5 Maven package
        id: cacheNether3
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/org/bukkit/craftbukkit/1.16.5-R0.1-SNAPSHOT/
          key: ${{ runner.os }}-1.16.5
          restore-keys: ${{ runner.os }}-1.16.5
      - name: Cache 1.17.1 Maven package
        id: cacheGoats
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository/org/spigotmc/spigot/1.17.1-R0.1-SNAPSHOT/
            ~/.m2/repository/org/spigotmc/spigot-parent/
            ~/.m2/repository/org/spigotmc/minecraft-server/
          key: ${{ runner.os }}-spigot-1.17.1-all
          restore-keys: ${{ runner.os }}-spigot-1.17.1-all
      - name: Cache 1.18 Maven package
        id: cacheCaves
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository/org/spigotmc/spigot/1.18-R0.1-SNAPSHOT/
            ~/.m2/repository/org/spigotmc/spigot-parent/
            ~/.m2/repository/org/spigotmc/minecraft-server/
          key: ${{ runner.os }}-spigot-1.18-all
          restore-keys: ${{ runner.os }}-spigot-1.18-all

      - name: Build with Maven
        run: mvn -T 1C -B package --file pom.xml

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
