name: Publish package to GitHub Packages

on:
  workflow_dispatch:
  release:
    types: [created, prereleased]

jobs:
  # Build Movecraft
  publish:
    runs-on: ubuntu-latest
    needs: ./.github/workflows/maven.yml

    steps:
    - name: Checkout Movecraft
      uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
    - name: Cache 1.14.4 Maven package
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository/org/bukkit/craftbukkit/1.14.4-R0.1-SNAPSHOT/
        key: ${{ runner.os }}-v1_14_R1
        restore-keys: ${{ runner.os }}-v1_14_R1
    - name: Cache 1.16.5 Maven package
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository/org/bukkit/craftbukkit/1.16.5-R0.1-SNAPSHOT/
        key: ${{ runner.os }}-v1_16_R3
        restore-keys: ${{ runner.os }}-v1_16_R3
    - name: Cache 1.17.1 Maven package
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository/org/spigotmc/spigot/1.17.1-R0.1-SNAPSHOT/
          ~/.m2/repository/org/spigotmc/spigot-parent/
          ~/.m2/repository/org/spigotmc/minecraft-server/
        key: ${{ runner.os }}-v1_17_R1
        restore-keys: ${{ runner.os }}-v1_17_R1
    - name: Cache 1.18.2 Maven package
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository/org/spigotmc/spigot/1.18.2-R0.1-SNAPSHOT/
          ~/.m2/repository/org/spigotmc/spigot-parent/
          ~/.m2/repository/org/spigotmc/minecraft-server/
        key: ${{ runner.os }}-v1_18_R2
        restore-keys: ${{ runner.os }}-v1_18_R2
    - name: Cache 1.19.2 Maven package
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository/org/spigotmc/spigot/1.19.2-R0.1-SNAPSHOT/
          ~/.m2/repository/org/spigotmc/spigot-parent/
          ~/.m2/repository/org/spigotmc/minecraft-server/
        key: ${{ runner.os }}-v1_19_R1
        restore-keys: ${{ runner.os }}-v1_19_R1
    - name: Cache 1.19.3 Maven package
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository/org/spigotmc/spigot/1.19.3-R0.1-SNAPSHOT/
          ~/.m2/repository/org/spigotmc/spigot-parent/
          ~/.m2/repository/org/spigotmc/minecraft-server/
        key: ${{ runner.os }}-v1_19_R2
        restore-keys: ${{ runner.os }}-v1_19_R2

    - name: Build with Maven
      run: mvn -T 1C -B package --file pom.xml

    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
